general {
        colors = true
        interval = 5
}

order += "cpu_usage"
order += "memory"
order += "disk /"
order += "time"

cpu_usage {
        format = "CPU %usage"
}

memory {
        format = "RAM %used/%total"
}

disk "/" {
        format = "SSD %avail"
}

time {
        format = "%H:%M"
}
