# SuperRice performance mode: lightweight transparency, low overhead
backend = "glx";
vsync = true;
use-damage = true;
unredir-if-possible = true;

corner-radius = 0;
shadow = false;
fading = false;
detect-client-opacity = true;

blur-method = "none";
blur-background = false;
blur-background-frame = false;
blur-background-fixed = false;

inactive-opacity = 0.99;
active-opacity = 1.0;
frame-opacity = 0.98;

opacity-rule = [
  "94:class_g = 'Rofi'",
  "94:class_g = 'SuperRiceTips'",
  "95:class_g = 'eww'",
  "95:class_g = 'Eww'"
];

animations = false;

wintypes:
{
  tooltip = { fade = false; shadow = false; opacity = 1.0; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; };
  dnd = { shadow = false; };
};
