# SuperRice light mode: fast + smooth
backend = "glx";
vsync = true;
use-damage = true;
unredir-if-possible = true;

corner-radius = 9;
shadow = true;
shadow-radius = 9;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.16;

shadow-exclude = [
  "class_g = 'i3-frame'",
  "window_type = 'dock'",
  "name = 'Notification'"
];

detect-client-opacity = true;
fading = true;
fade-in-step = 0.045;
fade-out-step = 0.045;
fade-delta = 8;

blur-method = "none";
blur-background = false;
blur-background-frame = false;
blur-background-fixed = false;

inactive-opacity = 0.985;
active-opacity = 1.0;
frame-opacity = 0.985;

opacity-rule = [
  "93:class_g = 'Rofi'",
  "93:class_g = 'SuperRiceTips'",
  "97:class_g = 'SuperRiceSplash'"
];

animations = false;

wintypes:
{
  tooltip = { fade = false; shadow = false; opacity = 0.97; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 0.97; };
  dropdown_menu = { opacity = 0.97; };
};
